## Lecture 2 - Numpy - 1D-2D
## Assignment 1

In [1]:
# Câu 1: Tạo và thao tác ở mảng 2D
# a) Tạo một ma trận 2 chiều có kích thước 4x4 với các giá trị ngẫu nhiên từ 1 đến 16.
import numpy as np
arr = np.random.randint(1, 17, (4, 4))
print(arr)

[[16  2 15  3]
 [ 4 15 16 14]
 [12 10  7 16]
 [11 15  8  6]]


In [2]:
# b) Dựa vào ma trận 2D ở câu a, truy cập và in ra như sau: (i) dữ liệu của hàng thứ 2, và (ii) cột thứ 3
print(arr[1,2])

16


In [9]:
# c) Tạo ra mảng mới dựa vào ma trận 2D ở câu a nhưng chỉ lấy từ hàng 1 đến 3 và cột 2 đến 4d
a =arr[:3, 1:4]
print(a)

[[ 2 15  3]
 [15 16 14]
 [10  7 16]]


In [12]:
# d) Dựa vào ma trận 2D ở câu a, thay đổi giá trị của cột thứ 0 thành giá trị 10
arr[:,0]=10
print(arr)

[[10  2 15  3]
 [10 15 16 14]
 [10 10  7 16]
 [10 15  8  6]]


In [14]:
# e) Dựa vào ma trận 2D ở câu a, Tính tổng của mỗi hàng
arr1=np.sum(arr,axis=1)
print("Ket qua: ",arr1)

Ket qua:  [30 55 43 39]


In [15]:
# f) Dựa vào ma trận 2D ở câu a, truy cập và in ra các phần tử lớn hơn giá trị trung bình
tb=np.mean(arr)
print(arr[arr>tb])


[15 15 16 14 16 15]


##### **QUESTION 2**
Dựa vào `np.arange` và `np.reshape` để tạo ra ma trận 3x3 với kết quả cụ thể như sau:
$$
\begin{bmatrix}
    10 & 11 & 12\\
    13 & 14 & 15\\
    16 & 17 & 18
\end{bmatrix}\\
$$
Dựa vào ma trận vừa tạo, Hãy tính tổng theo từng dòng

In [17]:
# Trả lời câu 2:
import numpy as np
arr = np.arange(10, 19)
matrix = np.reshape(arr, (3, 3))
print(matrix)


[[10 11 12]
 [13 14 15]
 [16 17 18]]


#### Câu 3
>Giải hệ phương trình sau:
\begin{equation}
    2x+y-z   =8\\
    4x-6y+2z =-3\\
    2x+8y-3z =3
\end{equation}

In [18]:
# Trả lời câu 3:
A=np.array([[2,1,-1],[4,-6,2],[2,8,-3]])
B=np.array([8,-3,3])
print("________")
X=np.dot(np.linalg.pinv(A),np.transpose(B))
print("Ket qua: ")
print(X)

________
Ket qua: 
[ -0.79166667  -4.83333333 -14.41666667]


## Assignment 2 - Loại dữ liệu tự định nghĩa

Tạo một đối tượng có tên là sản phẩm với các thuộc tính như sau: mã sản phẩm (masp), tên sản phẩm (tensp), và giá sản phẩm (price), số lượng (soluong). Dữ liệu cụ thể như sau:


(1, 'Máy tính', 1200.50,10),
(2, 'Điện thoại Iphone 11', 699.99,20),
(3, 'USB', 89.95,20),
(4, 'Loa ', 499.50,30),
(5, 'Màn hình', 799.00,50)


Yêu cầu:

a) Tìm sản phẩm có giá cao nhất

b) Tính giá trung bình của tất cả sản phẩm

c) Tính doanh số bán, biết rằng doanh số bán bằng số lượng x đơn giá

d) Hiện thị thông tin sản phẩm gồm có tên sản phẩm và giá sản phẩm

In [32]:
# a) Tìm sản phẩm có giá cao nhất
import numpy as np

# Câu 1
# Dữ liệu sản phẩm
product_data = [
    (1, 'Máy tính', 1200.50, 10),
    (2, 'Điện thoại Iphone 11', 699.99, 20),
    (3, 'USB', 89.95, 20),
    (4, 'Loa', 499.50, 30),
    (5, 'Màn hình', 799.00, 50)
]

# a) Tìm sản phẩm có giá cao nhất
products = np.array(product_data, dtype=[('masp', int), ('tensp', 'U30'), ('price', float), ('soluong', int)])

max_price_product = products[np.argmax(products['price'])]
print("Sản phẩm có giá cao nhất:")
print("Mã sản phẩm:", max_price_product['masp'])
print("Tên sản phẩm:", max_price_product['tensp'])
print("Giá sản phẩm:", max_price_product['price'])
print("Số lượng:", max_price_product['soluong'])
print()


Sản phẩm có giá cao nhất:
Mã sản phẩm: 1
Tên sản phẩm: Máy tính
Giá sản phẩm: 1200.5
Số lượng: 10



In [33]:
# b) Tính giá trung bình của tất cả sản phẩm
average_price = np.mean(products['price'])
print("Giá trung bình của tất cả sản phẩm:", average_price)
print()

Giá trung bình của tất cả sản phẩm: 657.788



In [34]:
#c) Tính doanh số bán, biết rằng doanh số bán bằng số lượng x đơn giá
total_revenue = np.sum(products['price'] * products['soluong'])
print("Tổng doanh số bán:", total_revenue)
print()


Tổng doanh số bán: 82738.8



In [12]:
# d) Hiện thị thông tin sản phẩm gồm có tên sản phẩm và giá sản phẩm
# Hàm hiển thị thông tin chi tiết về mỗi sản phẩm
print("Thông tin sản phẩm (tên và giá):")
for product in products:
    print("Tên sản phẩm:", product['tensp'])
    print("Giá sản phẩm:", product['price'])
    print()


## Assignment 3 - Tổng hợp
Dữ liệu của cầu thủ chơi bóng chày như sau: chiều cao (cột 1) tính theo inch và cân nặng (cột 2) tính theo pounds của các cầu thủ.

In [21]:
import numpy as np
# dữ liệu baseball
baseball = [[74, 180], [74, 215], [72, 210], [72, 210], [73, 188], [69, 176], [69, 209], [71, 200], [76, 231], [71, 180], [73, 188], [73, 180], [74, 185], [74, 160], [69, 180], [70, 185], [73, 189], [75, 185], [78, 219], [79, 230], [76, 205], [74, 230], [76, 195], [72, 180], [71, 192], [75, 225], [77, 203], [74, 195], [73, 182], [74, 188], [78, 200], [73, 180], [75, 200], [73, 200], [75, 245], [75, 240], [74, 215], [69, 185], [71, 175], [74, 199], [73, 200], [73, 215], [76, 200], [74, 205], [74, 206], [70, 186], [72, 188], [77, 220], [74, 210], [70, 195], [73, 200], [75, 200], [76, 212], [76, 224], [78, 210], [74, 205], [74, 220], [76, 195], [77, 200], [81, 260], [78, 228], [75, 270], [77, 200], [75, 210], [76, 190], [74, 220], [72, 180], [72, 205], [75, 210], [73, 220], [73, 211], [73, 200], [70, 180], [70, 190], [70, 170], [76, 230], [68, 155], [71, 185], [72, 185], [75, 200], [75, 225], [75, 225], [75, 220], [68, 160], [74, 205], [78, 235], [71, 250], [73, 210], [76, 190], [74, 160], [74, 200], [79, 205], [75, 222], [73, 195], [76, 205], [74, 220], [74, 220], [73, 170], [72, 185], [74, 195], [73, 220], [74, 230], [72, 180], [73, 220], [69, 180], [72, 180], [73, 170], [75, 210], [75, 215], [73, 200], [72, 213], [72, 180], [76, 192], [74, 235], [72, 185], [77, 235], [74, 210], [77, 222], [75, 210], [76, 230], [80, 220], [74, 180], [74, 190], [75, 200], [78, 210], [73, 194], [73, 180], [74, 190], [75, 240], [76, 200], [71, 198], [73, 200], [74, 195], [76, 210], [76, 220], [74, 190], [73, 210], [74, 225], [70, 180], [72, 185], [73, 170], [73, 185], [73, 185], [73, 180], [71, 178], [74, 175], [74, 200], [72, 204], [74, 211], [71, 190], [74, 210], [73, 190], [75, 190], [75, 185], [79, 290], [73, 175], [75, 185], [76, 200], [74, 220], [76, 170], [78, 220], [74, 190], [76, 220], [72, 205], [74, 200], [76, 250], [74, 225], [75, 215], [78, 210], [75, 215], [72, 195], [74, 200], [72, 194], [74, 220], [70, 180], [71, 180], [70, 170], [75, 195], [71, 180], [71, 170], [73, 206], [72, 205], [71, 200], [73, 225], [72, 201], [75, 225], [74, 233], [74, 180], [75, 225], [73, 180], [77, 220], [73, 180], [76, 237], [75, 215], [74, 190], [76, 235], [75, 190], [73, 180], [71, 165], [76, 195], [75, 200], [72, 190], [71, 190], [77, 185], [73, 185], [74, 205], [71, 190], [72, 205], [74, 206], [75, 220], [73, 208], [72, 170], [75, 195], [75, 210], [74, 190], [72, 211], [74, 230], [71, 170], [70, 185], [74, 185], [77, 241], [77, 225], [75, 210], [75, 175], [78, 230], [75, 200], [76, 215], [73, 198], [75, 226], [75, 278], [79, 215], [77, 230], [76, 240], [71, 184], [75, 219], [74, 170], [69, 218], [71, 190], [76, 225], [72, 220], [72, 176], [70, 190], [72, 197], [73, 204], [71, 167], [72, 180], [71, 195], [73, 220], [72, 215], [73, 185], [74, 190], [74, 205], [72, 205], [75, 200], [74, 210], [74, 215], [77, 200], [75, 205], [73, 211], [72, 190], [71, 208], [74, 200], [77, 210], [75, 232], [75, 230], [75, 210], [78, 220], [78, 210], [74, 202], [76, 212], [78, 225], [76, 170], [70, 190], [72, 200], [80, 237], [74, 220], [74, 170], [71, 193], [70, 190], [72, 150], [71, 220], [74, 200], [71, 190], [72, 185], [71, 185], [74, 200], [69, 172], [76, 220], [75, 225], [75, 190], [76, 195], [73, 219], [76, 190], [73, 197], [77, 200], [73, 195], [72, 210], [72, 177], [77, 220], [77, 235], [71, 180], [74, 195], [74, 195], [73, 190], [78, 230], [75, 190], [73, 200], [70, 190], [74, 190], [72, 200], [73, 200], [73, 184], [75, 200], [75, 180], [74, 219], [76, 187], [73, 200], [74, 220], [75, 205], [75, 190], [72, 170], [73, 160], [73, 215], [72, 175], [74, 205], [78, 200], [76, 214], [73, 200], [74, 190], [75, 180], [70, 205], [75, 220], [71, 190], [72, 215], [78, 235], [75, 191], [73, 200], [73, 181], [71, 200], [75, 210], [77, 240], [72, 185], [69, 165], [73, 190], [74, 185], [72, 175], [70, 155], [75, 210], [70, 170], [72, 175], [72, 220], [74, 210], [73, 205], [74, 200], [76, 205], [75, 195], [80, 240], [72, 150], [75, 200], [73, 215], [74, 202], [74, 200], [73, 190], [75, 205], [75, 190], [71, 160], [73, 215], [75, 185], [74, 200], [74, 190], [72, 210], [74, 185], [74, 220], [74, 190], [73, 202], [76, 205], [75, 220], [72, 175], [73, 160], [73, 190], [73, 200], [72, 229], [72, 206], [72, 220], [72, 180], [71, 195], [75, 175], [75, 188], [74, 230], [73, 190], [75, 200], [79, 190], [74, 219], [76, 235], [73, 180], [74, 180], [74, 180], [72, 200], [74, 234], [74, 185], [75, 220], [78, 223], [74, 200], [74, 210], [74, 200], [77, 210], [70, 190], [73, 177], [74, 227], [73, 180], [71, 195], [75, 199], [71, 175], [72, 185], [77, 240], [74, 210], [70, 180], [77, 194], [73, 225], [72, 180], [76, 205], [71, 193], [76, 230], [78, 230], [75, 220], [73, 200], [78, 249], [74, 190], [79, 208], [75, 245], [76, 250], [72, 160], [75, 192], [75, 220], [70, 170], [72, 197], [70, 155], [74, 190], [71, 200], [76, 220], [73, 210], [76, 228], [71, 190], [69, 160], [72, 184], [72, 180], [69, 180], [73, 200], [69, 176], [73, 160], [74, 222], [74, 211], [72, 195], [71, 200], [72, 175], [72, 206], [76, 240], [76, 185], [76, 260], [74, 185], [76, 221], [75, 205], [71, 200], [72, 170], [71, 201], [73, 205], [75, 185], [76, 205], [75, 245], [71, 220], [75, 210], [74, 220], [72, 185], [73, 175], [73, 170], [73, 180], [73, 200], [76, 210], [72, 175], [76, 220], [73, 206], [73, 180], [73, 210], [75, 195], [75, 200], [77, 200], [73, 164], [72, 180], [75, 220], [70, 195], [74, 205], [72, 170], [80, 240], [71, 210], [71, 195], [74, 200], [74, 205], [73, 192], [75, 190], [76, 170], [73, 240], [77, 200], [72, 205], [73, 175], [77, 250], [76, 220], [71, 224], [75, 210], [73, 195], [74, 180], [77, 245], [71, 175], [72, 180], [73, 215], [69, 175], [73, 180], [70, 195], [74, 230], [76, 230], [73, 205], [73, 215], [75, 195], [73, 180], [79, 205], [74, 180], [73, 190], [74, 180], [77, 190], [75, 190], [74, 220], [73, 210], [77, 255], [73, 190], [77, 230], [74, 200], [74, 205], [73, 210], [77, 225], [74, 215], [77, 220], [75, 205], [77, 200], [75, 220], [71, 197], [74, 225], [70, 187], [79, 245], [72, 185], [72, 185], [70, 175], [74, 200], [74, 180], [72, 188], [73, 225], [72, 200], [74, 210], [74, 245], [76, 213], [82, 231], [74, 165], [74, 228], [70, 210], [73, 250], [73, 191], [74, 190], [77, 200], [72, 215], [76, 254], [73, 232], [73, 180], [72, 215], [74, 220], [74, 180], [71, 200], [72, 170], [75, 195], [74, 210], [74, 200], [77, 220], [70, 165], [71, 180], [73, 200], [76, 200], [71, 170], [75, 224], [74, 220], [72, 180], [76, 198], [79, 240], [76, 239], [73, 185], [76, 210], [78, 220], [75, 200], [76, 195], [72, 220], [72, 230], [73, 170], [73, 220], [75, 230], [71, 165], [76, 205], [70, 192], [75, 210], [74, 205], [75, 200], [73, 210], [71, 185], [71, 195], [72, 202], [73, 205], [73, 195], [72, 180], [69, 200], [73, 185], [78, 240], [71, 185], [73, 220], [75, 205], [76, 205], [70, 180], [74, 201], [77, 190], [75, 208], [79, 240], [72, 180], [77, 230], [73, 195], [75, 215], [75, 190], [75, 195], [73, 215], [73, 215], [76, 220], [77, 220], [75, 230], [70, 195], [71, 190], [71, 195], [75, 209], [74, 204], [69, 170], [70, 185], [75, 205], [72, 175], [75, 210], [73, 190], [72, 180], [72, 180], [72, 160], [76, 235], [75, 200], [74, 210], [69, 180], [73, 190], [72, 197], [72, 203], [75, 205], [77, 170], [76, 200], [80, 250], [77, 200], [76, 220], [79, 200], [71, 190], [75, 170], [73, 190], [76, 220], [77, 215], [73, 206], [76, 215], [70, 185], [75, 235], [73, 188], [75, 230], [70, 195], [69, 168], [71, 190], [72, 160], [72, 200], [73, 200], [70, 189], [70, 180], [73, 190], [76, 200], [75, 220], [72, 187], [73, 240], [79, 190], [71, 180], [72, 185], [74, 210], [74, 220], [74, 219], [72, 190], [76, 193], [76, 175], [72, 180], [72, 215], [71, 210], [72, 200], [72, 190], [70, 185], [77, 220], [74, 170], [72, 195], [76, 205], [71, 195], [76, 210], [71, 190], [73, 190], [70, 180], [73, 220], [73, 190], [72, 186], [71, 185], [71, 190], [71, 180], [72, 190], [72, 170], [74, 210], [74, 240], [74, 220], [71, 180], [72, 210], [75, 210], [72, 195], [71, 160], [72, 180], [72, 205], [72, 200], [72, 185], [74, 245], [74, 190], [77, 210], [75, 200], [73, 200], [75, 222], [73, 215], [76, 240], [72, 170], [77, 220], [75, 156], [72, 190], [71, 202], [71, 221], [75, 200], [72, 190], [73, 210], [73, 190], [71, 200], [70, 165], [75, 190], [71, 185], [76, 230], [73, 208], [68, 209], [71, 175], [72, 180], [74, 200], [77, 205], [72, 200], [76, 250], [78, 210], [81, 230], [72, 244], [73, 202], [76, 240], [72, 200], [72, 215], [74, 177], [76, 210], [73, 170], [76, 215], [75, 217], [70, 198], [71, 200], [74, 220], [72, 170], [73, 200], [76, 230], [76, 231], [73, 183], [71, 192], [68, 167], [71, 190], [71, 180], [74, 180], [77, 215], [69, 160], [72, 205], [76, 223], [75, 175], [76, 170], [75, 190], [76, 240], [72, 175], [74, 230], [76, 223], [74, 196], [72, 167], [75, 195], [78, 190], [77, 250], [70, 190], [72, 190], [79, 190], [74, 170], [71, 160], [68, 150], [77, 225], [75, 220], [71, 209], [72, 210], [70, 176], [72, 260], [72, 195], [73, 190], [72, 184], [74, 180], [72, 195], [72, 195], [75, 219], [72, 225], [73, 212], [74, 202], [72, 185], [78, 200], [75, 209], [72, 200], [74, 195], [75, 228], [75, 210], [76, 190], [74, 212], [74, 190], [73, 218], [74, 220], [71, 190], [74, 235], [75, 210], [76, 200], [74, 188], [76, 210], [76, 235], [73, 188], [75, 215], [75, 216], [74, 220], [68, 180], [72, 185], [75, 200], [71, 210], [70, 220], [72, 185], [73, 231], [72, 210], [75, 195], [74, 200], [70, 205], [76, 200], [71, 190], [82, 250], [72, 185], [73, 180], [74, 170], [71, 180], [75, 208], [77, 235], [72, 215], [74, 244], [72, 220], [73, 185], [78, 230], [77, 190], [73, 200], [73, 180], [73, 190], [73, 196], [73, 180], [76, 230], [75, 224], [70, 160], [73, 178], [72, 205], [73, 185], [75, 210], [74, 180], [73, 190], [73, 200], [76, 257], [73, 190], [75, 220], [70, 165], [77, 205], [72, 200], [77, 208], [74, 185], [75, 215], [75, 170], [75, 235], [75, 210], [72, 170], [74, 180], [71, 170], [76, 190], [71, 150], [75, 230], [76, 203], [83, 260], [75, 246], [74, 186], [76, 210], [72, 198], [72, 210], [75, 215], [75, 180], [72, 200], [77, 245], [73, 200], [72, 192], [70, 192], [74, 200], [72, 192], [74, 205], [72, 190], [71, 186], [70, 170], [71, 197], [76, 219], [74, 200], [76, 220], [74, 207], [74, 225], [74, 207], [75, 212], [75, 225], [71, 170], [71, 190], [74, 210], [77, 230], [71, 210], [74, 200], [75, 238], [77, 234], [76, 222], [74, 200], [76, 190], [72, 170], [71, 220], [72, 223], [75, 210], [73, 215], [68, 196], [72, 175], [69, 175], [73, 189], [73, 205], [75, 210], [70, 180], [70, 180], [74, 197], [75, 220], [74, 228], [74, 190], [73, 204], [74, 165], [75, 216], [77, 220], [73, 208], [74, 210], [76, 215], [74, 195], [75, 200], [73, 215], [76, 229], [78, 240], [75, 207], [73, 205], [77, 208], [74, 185], [72, 190], [74, 170], [72, 208], [71, 225], [73, 190], [75, 225], [73, 185], [67, 180], [67, 165], [76, 240], [74, 220], [73, 212], [70, 163], [75, 215], [70, 175], [72, 205], [77, 210], [79, 205], [78, 208], [74, 215], [75, 180], [75, 200], [78, 230], [76, 211], [75, 230], [69, 190], [75, 220], [72, 180], [75, 205], [73, 190], [74, 180], [75, 205], [75, 190], [73, 195]]
print(len(baseball))

1015


In [24]:
# Câu 1: Tạo một 2D numpy array tên np_baseball từ baseball.
import numpy as np
np_baseball = np.array(baseball)
print(np_baseball)

[[ 74 180]
 [ 74 215]
 [ 72 210]
 ...
 [ 75 205]
 [ 75 190]
 [ 73 195]]


In [25]:
# Câu 2: Tạo một numpy array np_weight với dữ liệu được lấy từ cột hai của np_baseball.

# In danh sách các phần tử của np_weight.
np_weight = np_baseball[:, 1]

# In danh sách các phần tử của np_weight
print("Danh sách cân nặng của cầu thủ:", np_weight)


Danh sách cân nặng của cầu thủ: [180 215 210 ... 205 190 195]


In [26]:
# Câu 3: Cho biết chiều cao của vận động viên thứ 124, và in ra kết quả
height_124 = np_baseball[123, 0]
print("Chiều cao của cầu thủ thứ 124 là:", height_124)


Chiều cao của cầu thủ thứ 124 là: 75


In [30]:
# Câu 4: Cho biết chiều cao trung bình, cân nặng trung bình của các cầu thủ
nangtb = np.mean(np_baseball[:, 0])
caotb = np.mean(np_baseball[:, 1])
print("Chiều cao trung bình của các cầu thủ là:", caotb)
print("Cân nặng trung bình của các cầu thủ là:", nangtb)


Chiều cao trung bình của các cầu thủ là: 201.34876847290641
Cân nặng trung bình của các cầu thủ là: 73.6896551724138


In [31]:
# Câu 5: Bạn nhận xét gì về mối tương quan giữa chiều cao và cân nặng của các cầu thủ: 
# Có/ không có tương quan, tương quan thuận/nghịch
r = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])[0, 1]
print("Hệ số tương quan giữa chiều cao và cân nặng là:", r)

# Nhận xét về mối tương quan
if r > 0:
    print("Có mối tương quan thuận giữa chiều cao và cân nặng.")
else:
    print("Có mối tương quan nghịch giữa chiều cao và cân nặng.")

Hệ số tương quan giữa chiều cao và cân nặng là: 0.5315393226146091
Có mối tương quan thuận giữa chiều cao và cân nặng.
